import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rock-wool Insulation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          'bg-[##f0f0f0] bg-auto bg-scroll bg-left-top bg-repeat text-left text-base font-normal leading-6 text-[#212529]',
          inter.className
        )}
      >
        {children}
        <div id='modal'></div>
      </body>
    </html>
  );
}
