import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import clsx from 'clsx';

const font = Poppins({
  weight: ['400', '700'], // Specify the desired font weights
  style: 'normal', // Specify the font style (normal or italic)
  subsets: ['latin'], // Specify subsets if needed
});

export const metadata: Metadata = {
  title: 'Rock-wool Insulation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          'bg-[##f0f0f0] bg-auto bg-scroll bg-left-top bg-repeat text-left text-base font-normal leading-6 text-[#212529]',
          font.className
        )}
      >
        {children}
        <div id='modal'></div>
      </body>
    </html>
  );
}
